{"name": "test_fail17", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail17():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:17: AssertionError"}, "start": 1694074744895, "stop": 1694074744896, "uuid": "057d617d-0d49-43ae-bf8e-9f5c865d63d9", "historyId": "4dc7b3c768c02706c892e38ed79d2a11", "testCaseId": "4dc7b3c768c02706c892e38ed79d2a11", "fullName": "tests.simple.test_fail#test_fail17", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}