{"name": "test_fail12", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail12():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:2: AssertionError"}, "start": 1694074683460, "stop": 1694074683460, "uuid": "490b3ec9-07f2-49fd-9d11-9056fc700991", "historyId": "53f28bc186052642b7770996b373ee6e", "testCaseId": "53f28bc186052642b7770996b373ee6e", "fullName": "tests.simple.test_fail#test_fail12", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}