{"name": "test_fail13", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail13():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:5: AssertionError"}, "start": 1694074692533, "stop": 1694074692533, "uuid": "e50ad913-c043-4f40-bac8-c33978b7fb4e", "historyId": "f66e5038d67d873d766757665b95b1c4", "testCaseId": "f66e5038d67d873d766757665b95b1c4", "fullName": "tests.simple.test_fail#test_fail13", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}