{"name": "test_fail15", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail15():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:11: AssertionError"}, "start": 1694074720688, "stop": 1694074720689, "uuid": "c9b2b2e8-a134-4207-905a-200a670ee4e6", "historyId": "307fff1d2ff0da5053e71ef8003d0e51", "testCaseId": "307fff1d2ff0da5053e71ef8003d0e51", "fullName": "tests.simple.test_fail#test_fail15", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}