{"name": "test_fail16", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail16():\n>       assert False\nE       assert False\n\ntests\\simple\\test_fail.py:14: AssertionError"}, "start": 1694074735519, "stop": 1694074735519, "uuid": "019fcb94-86fa-476d-b300-882b3c1be0cd", "historyId": "a1904772a38a210acc9313e29f74e801", "testCaseId": "a1904772a38a210acc9313e29f74e801", "fullName": "tests.simple.test_fail#test_fail16", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "CHIRKINAA-E15G2"}, {"name": "thread", "value": "34640-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}]}